<h1>3 - Loading Data</h1>
<i>Designing loading pipelines for various kinds of file types.</i>

### Load imports and secrets

In [1]:
import os
import sys
from dotenv import load_dotenv

from openai import OpenAI
from anthropic import Anthropic

load_dotenv()

True

In [2]:
print("OPENAI Ключ найден:" if "OPENAI_API_KEY" in os.environ else "Ключ не найден")
print("ANTHROPIC Ключ найден:" if "ANTHROPIC_API_KEY" in os.environ else "Ключ не найден")
print("GOOGLE Ключ найден:" if "GOOGLE_API_KEY" in os.environ else "Ключ не найден")

OPENAI Ключ найден:
ANTHROPIC Ключ найден:
GOOGLE Ключ найден:

### 1.1 Loading Word Files in Python

Option 1: load word files using the `python_docx` library

In [4]:
import os
import requests
from docx import Document
from io import BytesIO

file_path = "../../datasets/word_files/2023_Jan_7_Feature_Engineering_Techniques.docx"
doc = Document(file_path)

text = []
for paragraph in doc.paragraphs:
    text.append(paragraph.text)

full_text = "\n".join(text)

In [7]:
print(full_text)

7 of the Most Used Feature Engineering Techniques
Hands-on Feature Engineering with Scikit-Learn, Tensorflow, Pandas and Scipy
7 of the most used Feature Engineering Techniques — Image by the author

Table of content
Introduction
1. Encoding
 1.1 Label Encoding using Scikit-learn
 1.2 One-Hot Encoding using Scikit-learn, Pandas and Tensorflow
2. Feature Hashing
 2.1 Feature Hashing using Scikit-learn
3. Binning / Bucketizing
 3.1 Bucketizing using Pandas
 3.2 Bucketizing using Tensorflow
 3.3 Bucketizing using Scikit-learn
4. Transformer
 4.1 Log-Transformer using Numpy
 4.2 Box-Cox Function using Scipy
5. Normalize / Standardize
 5.1 Normalize and Standardize using Scikit-learn
6. Feature Crossing
 6.1 Feature Crossing in Polynomial Regression
 6.2 Feature Crossing and the Kernel-Trick
7. Principal Component Analysis (PCA)
 7.1 PCA using Scikit-learn
Summary
References

Introduction
Feature engineering describes the process of formulating relevant features that describe the underlying data science problem as accurately as possible and make it possible for algorithms to understand and learn patterns. In other words:
Features you provide serve as a way to communicate your own understanding and knowledge about the world to your model
Each feature describes a kind of information “piece”. The sum of these pieces allows the algorithm to draw conclusions about the target variables — at least if you have a data set that actually contains information about your target variable.
According to the Forbes magazine, Data Scientists spend about 80% of their time collecting and preparing relevant data, with the data cleaning and data organizing alone taking up about 60% of the time.
But this time is well spent.
I believe that the quality of the data, as well as the proper preparation of the data set features, have a greater impact on the success of a machine learning model than any other part of the ML pipeline:
A standard Machine Learning pipeline — Inspired by [Sarkar et al., 2018]
What Forbes magazine considers as “cleaning and organizing” is usually broken down into two to three subcategories in the ML pipeline (I have highlighted them with a yellow background in the image above):
(1) Data (Pre-)Processing: The initial preparation of the data — for example, smoothing a signal, dealing with outliers, etc.
(2) Feature engineering: Defining input features for our model — e.g., by converting an (acoustic) signal to the frequency domain using the fast Fourier transform (FFT) allows us to extract crucial information from the raw signal.
(3) Feature Selection: Selection of features that have a significant impact on the target variable. By selecting the important features and thus reducing the dimensionality, we can significantly reduce the modeling costs and increase the robustness and performance of the model.
Why do we need Feature Engineering?
Andrew Ng frequently advocates a so-called data-centric approach, which emphasizes the importance of selecting and curating data, rather than simply trying to collect more and more data. The goal is to ensure that the data is of high quality and relevance to the problem being addressed and to continually improve the data set through data cleaning, feature engineering and data augmentation.
Why do we need feature engineering and a data-centric approach when we have Deep Learning?
This approach is particularly useful for use cases where it is costly or otherwise difficult to collect large amounts of data. [Brown, 2022] This might be the case when the data is difficult to access, or when there are strict regulations or other barriers to collecting and storing large amounts of data, e.g.:
In the manufacturing sector, equipping production facilities with comprehensive sensor technology and connecting them to databases is expensive. As a result, many plants do not yet collect data at all. Even when machines are able to collect and store data, they are rarely connected to a central data lake.
In the supply chain context, every company has only a certain number of orders that it processes every day. So if we want to predict the demand for a product that is in very irregular demand, we sometimes have only a few data points available.
In such areas, feature engineering probably has the greatest leverage to increase the performance of the models. Here, the creativity of the engineers and data scientists is required to enhance the data set quality to a sufficient level. The process is rarely straightforward, but rather experimental and iterative.
When humans analyze data, they often use their past knowledge and experience to help them understand patterns and make predictions. For example, if someone is trying to estimate the temperature in different countries, they might consider the location of the country relative to the equator, since they know that temperatures tend to be higher near the equator.
However, a machine learning model does not have the same inherent understanding of concepts and relationships as a human does. It can only learn from the data it is given. Therefore, any background information or context that a human would use to solve a problem must be explicitly included in the data set in a numerical form.
Average yearly temperature per country [Wikimedia]
So what data do we need to make the model smarter than a human?
We could use the Google Maps API to find the location coordinates (longitude and latitude) of each country. Additionally, we can gather information about the altitude of the region and the distance from the nearest body of water for each country. By collecting this extra data, we hope to identify and consider possible factors that could affect the temperature in each country.
Let’s say we have collected some data that might have an impact on the temperature, what next?
Once we have enough data that describes the characteristics of the problem, we still have to make sure that the computer can understand the data. Categorical data, dates, etc. must be converted into numerical values.
In this article, I am describing a few commonly used techniques for preparing raw data. Some techniques are used to convert categorical data into numerical values that can be understood by the machine learning model, such as encoding and vectorizing. Other techniques are used to address the distribution of the data, such as transformers and binning, which can help to normalize or standardize the data in some way. Still, other techniques are used to reduce the dimensionality of the dataset by generating new features, such as hashing and principal component analysis (PCA).
Try it yourself…
If you want to follow the article and try the methods yourself, you can use the repo below, which contains the code snippets in a Jupyter Notebook and the data sets used:
GitHub - polzerdo55862/7-feature-engineering-techniques
You can't perform that action at this time. You signed in with another tab or window. You signed out in another tab or…github.com

1. Encoding
Feature encoding is a process used to transform categorical data into numerical values that can be understood by ML algorithms. There are several types of encoding, including label encoding and one-hot encoding.
Label and Hot Encoding — Image by the author
Label encoding involves assigning a numeric value to each categorical value. This can be effective if there is an inherent order to the categorical values, such as grades from A to F, which can be encoded as numeric values from 1 to 5 (or 6). However, if there is no inherent order to the categorical values, label encoding may not be the best approach.
Alternatively, you can use One-hot encoding to transform categorical values into numerical values. In one-hot encoding, the column of categorical values is split into several new columns, one for each unique categorical value.
For example, if the categorical values are grades from A to F:
we would have five new columns, one for each grade.
Each row in the dataset would have a value of 1 in the column corresponding to its grade and 0 in all the other columns.
This results in a so-called sparse matrix, where most of the values are 0.
The disadvantage of one-hot encoding is that it can significantly increase the size of the dataset, which can be a problem if the column you want to encode contains hundreds or thousands of unique categorical values.
In the following I am using Pandas, Scikit-learn or Tensorflow to apply label and one-hot encoding to your data set. For the example below, we are using the Census Income data set:
Data set: Census Income [License: CC0: Public Domain]
https://archive.ics.uci.edu/ml/datasets/census+income
https://www.kaggle.com/datasets/uciml/adult-census-income
The Census Income Data set describes the income of individuals in the United States. It includes their age, sex, marital status and other demographic information as well as their annual income, which is divided into two categories: over $50,000 or under $50,000.
For the labelling example, we are using the “education” column of the census data set, which describes the highest level of education achieved by individuals within the population. It contains information such as whether an individual has completed high school, completed college, earned a graduate degree, or some other form of education.
First, let’s load the data set:
import pandas as pd

# load dataset - census income
census_income = pd.read_csv(r'../input/income/train.csv')
1.1 Label Encoding using Scikit-learn
Label encoding is the simplest way to convert categorical values into numerical values. It is a simple process of assigning a numerical value to each category.
Label Encoding— Image by the author
You can find suitable libraries in Pandas, Scikit-Learn and Tensorflow. I am using the Scikit-Learns Label Encoder function. It is randomly assigning integers to the unique categorical values, which is the simplest way of encoding:
from sklearn import preprocessing

# define and fit LabelEncoder
le = preprocessing.LabelEncoder()
le.fit(census_income["education"])

# Use the trained LabelEncoder to label the education column
census_income["education_labeled"] = le.transform(census_income["education"])

display(census_income[["education", "education_labeled"]])

This way of encoding can cause problems for some algorithms because the assigned integers do not necessarily reflect any inherent order or relationship between the categories. For example, in the case described above, the algorithm may assume that the categories Doctorate (10) and HS-grad (11) are more similar to each other than categories Doctorate (10) and Bachelor (9) and that HS-grad (11) is “higher” than Doctorate (10).
Label Encoding result interpretation — Image by the author
If we have some knowledge about the specific domain or subject matter of a data set, we can use it to ensure that the label encoding process reflects any inherent order. For our example, we could try to label the education levels considering the order in which different degrees are obtained, e.g.:
Doctorate is a higher academic degree compared to a Master's and Bachelor's. The Master's is higher than the Bachelor's.

To apply this manual mapping to the data set, we can use the pandas.map function:
education_labels = {'Doctorate':5, 'Masters':4, 'Bachelors':3, 'HS-grad':2, '12th':1, '11th':0}

census_income['education_labeled_pandas']=census_income['education'].map(education_labels)

census_income[["education", "education_labeled_pandas"]]

But how does this affect the model-building process?
Let's build a simple linear regression model with the labeled encoded data:
For the figure below, the target variable is defined as the probability that an individual has an income of more than $50,000.
In the left figure, the categorical values (such as “Bachelor” and “Doctorate”) have been assigned randomly to numerical values.
In the right figure, the numerical values assigned to the categorical values reflect the order in which the degrees are typically obtained, with higher education degrees being assigned higher numerical values.
→ The right figure shows a clear correlation between education level and income, which could be represented by a simple linear model.
→ In contrast, the left figure shows a relationship between the education attribute and the target variable, which would require a more complex model to accurately represent. This could affect the interpretability of the results, increase the risk of overfitting and increase the computational effort required to fit the model.
Label Encoding: Linear Regression Model trained on ordered and unordered “education” feature — Image by the author
What do we do when values have no inherent order or we don’t have enough information to map it?
If the categorical values do not have an inherent order at all, it may be better to use a method of encoding that converts the categories into a set of numeric variables without introducing any bias. One-hot encoding is one suitable method.
1.2 One-Hot Encoding using Scikit-learn, Pandas and Tensorflow
One-hot encoding is a technique for converting categorical data into numerical data. It does this by creating a new binary column for each unique category in the data set and assigning a value of 1 to rows that belong to that category and a value of 0 to rows that do not.
→ This process helps to avoid introducing bias into the data by not assuming any inherent order between the categories.
One-Hot Encoding — Image by the author
The process of One-Hot Encoding is pretty straightforward. We could simply implement it by ourselves or use one of the existing functions. Scikit-learn has the .preprocessing.OneHotEncoder() function, Tensorflow the .one_hot() function, and Pandas the .get_dummies() function.
Pandas.get_dummies()
import pandas as pd

education_one_hot_pandas = pd.get_dummies(census_income["education"], prefix='education')
education_one_hot_pandas.head(2)
Sklearn.preprocessing.LabelBinarizer()
from sklearn import preprocessing

lb = preprocessing.LabelBinarizer()
lb.fit(census_income["education"])

education_one_hot_sklearn_binar = pd.DataFrame(lb.transform(census_income["education"]), columns=lb.classes_)
education_one_hot_sklearn_binar.head(2)
Sklearn.preprocessing.OneHotEncoder()
from sklearn.preprocessing import OneHotEncoder

# define and fit the OneHotEncoder
ohe = OneHotEncoder()
ohe.fit(census_income[['education']])

# transform the data
education_one_hot_sklearn = pd.DataFrame(ohe.transform(census_income[["education"]]).toarray(), columns=ohe.categories_[0])
education_one_hot_sklearn.head(3)
The problem with one-hot encoding is that it can lead to large and sparse datasets with high dimensionality.
Using one-hot encoding to convert a categorical feature with 10,000 unique values into numerical data would result in the creation of 10,000 new columns in the data set, each representing a different category. This can be a problem when working with large data sets, as it can quickly consume a lot of memory and computational resources.
If memory and computer power are limited, it may be necessary to reduce the number of features in the data set to avoid running into memory or performance issues.
How can we reduce dimensionality to save memory?
When doing this, it is important to try to minimize the loss of information as much as possible. This can be achieved by carefully selecting which features to retain or remove, by using techniques such as feature selection or dimensionality reduction to identify and remove redundant or irrelevant features. [Sklearn.org][Wikipedia, 2022]
In this article I am describing two possible ways how to reduce the dimensionality of your data set:
Feature Hashing — see section 2. Feature Hashing
Principal Component Analysis (PCA) — see section 7. PCA
Loss of information vs. speed vs. memory
There is probably not one “perfect” solution for reducing the number of dimensions in your data set. One method may be faster but may result in the loss of a lot of information, while the other method preserves more information but requires a lot of computing resources (which may also lead to memory issues).

2. Feature Hashing
Feature hashing is primarily a dimensionality reduction technique and is often used in Natural Language Processing. However, hashing can also be useful when we want to vectorize categorical features with several hundred and thousand unique categories. With hashing, we can limit the increase of dimensionality by assigning several unique values to the same hash value.
→ Hashing is thus a low-memory alternative to OneHotEncoding and other feature vectorizing methods.
Hashing works by applying a hash function to the features and using the hash values directly as indices, rather than building a hash table and looking up indices in it individually. The implementation in Sklearn is based on Weinberger [Weinberger et al., 2009].
We can break it down into 2 steps:
Step 1: the categorical values are first converted to a hash value using a hash function. The implementation in Scikit-learn uses the 32-bit variant of MurmurHash3 for this.
Hashing Trick — Image by the author


Step 2: Next, we reduce the dimensionality by applying a mod function to the feature values. Using the mod function, we calculate the remainder after dividing the hash value by n_features (the number of features of the output vector).
It is advisable to use a power of two as the n_features parameter; otherwise, the features will not map evenly to the columns.
Example: Census Income data set →Encoding the Education column
The “Education” column of the census income dataset contains 16 unique values:
With one-hot encoding, 16 columns will be added to the dataset, each representing one of the 16 unique values.
→ To reduce the dimensions, we set n_features to 8.
This inevitably leads to “collisions”, i.e. that different categorical values are mapped to the same hash columns. So in other words, we are assigning different values to the same bucket. Similar to what we are doing in Binning/Bucketizing (see section 3. Binning/Bucketizing). In feature hashing, we deal with collisions by simply chaining values that are assigned to the same bucket and storing them in a list (known as “separate chaining”).
Feature Hashing: Reducing the dimensionality by calculating the remainder as a new column index — Image by the author


A function that is doing the just described steps for us is the HashingVectorizer function from Scikit-learn.
2.1 Feature Hashing using Scikit-learn

sklearn.feature_extraction.text.HashingVectorizer

from sklearn.feature_extraction.text import HashingVectorizer



3. Binning / Bucketizing
Binning is used for both categorical and numerical data. As the name suggests, the goal is to map the values of the features to “bins” and replace the original value with the value that represents the bin.
For example, if we had a dataset with values ranging from 0 to 100 and we wanted to group those values into bins of size 10, we might create bins for values 0–9, 10–19, 20–29 and so on.
→ In this case, the original values would be replaced with the value that represents the bin to which they belong, such as 10, 20, 30, etc. This can help visualize and analyze the data.
Since we are reducing the number of unique values in the data set, it can help to:
prevent overfitting
increase the robustness of the model and mitigate the influence of anomalies
reduce the model complexity and the required resources to train the model
Systematic binning can help the algorithm to detect underlying patterns more easily and efficiently. It is especially helpful if we can already form a hypothesis before we are defining the bins.
Binning can be used for both numeric and categorical values, e.g.:
Bucketizing for categorical and numerical features — Image by the author
In the following, I describe how this might look for numeric and categorical attributes using three examples:

Option 2: load word files using the unstructured library

In [8]:
from unstructured.partition.docx import partition_docx
import pandas as pd

elements = partition_docx(filename=file_path)

list_of_elements = []

for element in elements:
    element_dict = {
        "element_id": element.id,
        "file_path": file_path,
        "category": element.category,  # e.g. "Title", "NarrativeText", "ListItem"
        "text": element.text,
        "last_modified": element.metadata.last_modified,
    }

    list_of_elements.append(element_dict)

elements_df = pd.DataFrame(list_of_elements)

In [9]:
elements_df.head()

,element_id,file_path,category,text,last_modified
0,135f726911a68beceb56d92e2b9d10bc,../../datasets/word_files/2023_Jan_7_Feature_E...,Title,7 of the Most Used Feature Engineering Techniques,2026-05-14T19:59:12
1,f275447183f11b993f2a87d4b428299b,../../datasets/word_files/2023_Jan_7_Feature_E...,Title,Hands-on Feature Engineering with Scikit-Learn...,2026-05-14T19:59:12
2,9dacd0881e31b366756a6cc20884f661,../../datasets/word_files/2023_Jan_7_Feature_E...,NarrativeText,7 of the most used Feature Engineering Techniq...,2026-05-14T19:59:12
3,3bec63fc43107e87aae98bbaf5313196,../../datasets/word_files/2023_Jan_7_Feature_E...,Title,Table of content,2026-05-14T19:59:12
4,b1b29811f875047fef0bab817d6325c5,../../datasets/word_files/2023_Jan_7_Feature_E...,UncategorizedText,Introduction,2026-05-14T19:59:12

### 1.2 Loading PDF Files

In [ ]:
# PyPDF2 Pillow
import PyPDF2
import pandas as pd

file_path = "../../datasets/pdf_files/2023_Jan_7_Feature_Engineering_Techniques.pdf"

with open(file_path, "rb") as file:
    reader = PyPDF2.PdfReader(file)

    # Initialize an empty string to store the extracted text
    list_of_pages = []
    page_counter = 1

    for page in reader.pages:
        page_dict = {
            "file_name": reader.metadata.get("/Title"),
            "producer": reader.metadata.get("/Producer"),
            "page_number": page_counter,
            "text": page.extract_text(),
            "images": page.images,
        }

        list_of_pages.append(page_dict)

        page_counter += 1

# Convert the list of pages to a pandas DataFrame
pages_df = pd.DataFrame(list_of_pages)

In [13]:
pages_df.head()

,file_name,producer,page_number,text,images
0,2023_Jan_7_Feature_Engineering_Techniques,Skia/PDF m131 Google Docs Renderer,1,7\nof\nthe\nMost\nUsed\nFeature\nEngineering\n...,"[File(name=X7.png, data: 1.9 kB)]"
1,2023_Jan_7_Feature_Engineering_Techniques,Skia/PDF m131 Google Docs Renderer,2,3.2\nBucketizing\nusing\nTensorflow\n3.3\nBuck...,[]
2,2023_Jan_7_Feature_Engineering_Techniques,Skia/PDF m131 Google Docs Renderer,3,A\nstandard\nMachine\nLearning\npipeline — Ins...,"[File(name=X17.png, data: 699 Byte)]"
3,2023_Jan_7_Feature_Engineering_Techniques,Skia/PDF m131 Google Docs Renderer,4,"●\nI\nn\nthe\nsupply\nchain\ncontext\n,\nevery...","[File(name=X20.png, data: 3.1 kB)]"
4,2023_Jan_7_Feature_Engineering_Techniques,Skia/PDF m131 Google Docs Renderer,5,Once\nwe\nhave\nenough\ndata\nthat\ndescribes\...,"[File(name=X26.png, data: 1.7 kB)]"

### 1.3 Loading and Handling CSV and Excel Files

In [16]:
# openpyxl pandas
import pandas as pd

file_path = "../../datasets/csv_files/census-income.xlsx"
df_excel = pd.read_excel(io=file_path)


def create_text_description_of_row(row):
    row["text_description"] = (
        f"""The candidate {row['age']} years old is working in the
            {row['workclass']} sector. The candidate was born in
            {row['native-country']}, is {row['marital-status']}
            and has a {row['relationship']} relationship.
            The candidate has a {row['education']} degree
            and is working as a {row['occupation']}.
            The income of the candidate is {row['income']}."""
    )

    return row


# Apply the function create_text_description_of_row to each row of the data frame
df_extended = df_excel.apply(create_text_description_of_row, axis=1)

In [17]:
df_extended["text_description"].head()

0    The candidate 39 years old is working in the\n...
1    The candidate 50 years old is working in the\n...
2    The candidate 38 years old is working in the\n...
3    The candidate 53 years old is working in the\n...
4    The candidate 28 years old is working in the\n...
Name: text_description, dtype: str

### 1.4 Querying a PostgreSQL Database

This section needs a PostgreSQL database to connect to.

**Note:** Make sure a PostgreSQL server is installed and running, either locally on your machine or on a remote host that you can connect to.

In [ ]:
import pandas as pd
from sqlalchemy import create_engine
from psycopg2 import OperationalError

# PostgreSQL connection parameters
username = "rag_user"
password = "raguserpassword123"
host = "localhost"
port = "5432"
database = "postgres"

connection_string = (
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

try:
    engine = create_engine(connection_string)
    with engine.connect() as connection:
        query = """SELECT * FROM categories ORDER BY category_id ASC """
        result = pd.read_sql(query, connection)
        print(result)
except OperationalError as e:
    print(f"Error connecting to PostgreSQL database: {e}")
    print("Please ensure the PostgreSQL server is running and accessible.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

### 1.5 Loading Audio Files by Using Speech-to-Text Models

In [22]:
import os
from openai import OpenAI

audio_file_path = "../../datasets/audio_files/harvard.wav"

# initialize the OpenAI client with your API key
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

with open(audio_file_path, "rb") as audio_file:
    transcription = client.audio.transcriptions.create(
        model="whisper-1", file=audio_file
    )

transcription

Transcription(text='The stale smell of old beer lingers. It takes heat to bring out the odor. A cold dip restores health and zest. A salt pickle tastes fine with ham. Tacos al pastor are my favorite. A zestful food is the hot cross bun.', logprobs=None, usage=UsageDuration(seconds=19.0, type='duration'))

### 1.6 Extracting Text from Images and PDFs Using OCR

install Tesseract and its developer tools on Ubuntu \
sudo apt install tesseract-ocr\
sudo apt install libtesseract-dev\

In [24]:
# pdf2image pytesseract pillow
from pdf2image import convert_from_path
from PIL import Image
import pytesseract

image = Image.open(
    fp="../../datasets/images/example_finance_reporting_slide.png"
)

text = pytesseract.image_to_string(image)

In [26]:
print(text)

Sales volume growth driven by EMEA 18/19

Business Development
1,926

628 e Sales volume growth driven by

EMEA with sales activity up to 2.3x
YoY

e Sales activity in 20 countries during
Q2 19
e US (28%), Spain (20%), India
(15%) and Norway (11%) are the
main contributors to the Q2 19
sales volume

~
Ww
x
—
®
£
2
i}
>
7)
2
©
7)

Q4 18 Q119

Americas TT EMEA

If you have a scanned PDF, you can load it and convert each page into an image, and
then use Tesseract to extract the text from each page:\

sudo apt install poppler-utils

In [28]:
from pdf2image import convert_from_path
from PIL import Image
import pytesseract

file_path = (
    "../../datasets/pdf_files/2023_Jan_7_Feature_Engineering_Techniques.pdf"
)

images = convert_from_path(pdf_path=file_path)

text = []
for i, image in enumerate(images):
    page_text = pytesseract.image_to_string(image)
    text.append(page_text)

print(text)

['7 of the Most Used Feature Engineering Techniques\n\nHands-on Feature Engineering with Scikit-Learn, Tensorflow, Pandas and Scipy\n\n7 of the most used Feature Engineering Techniques—Image by the author\n\nTable of content\n\nIntroduction\n\n1. Encoding\n\n1.1 Label Encoding using Scikit-learn\n\n1.2 One-Hot Encoding using Scikit-learn, Pandas and Tensorflow\n2. Feature Hashing\n\n2.1 Feature Hashing using Scikit-learn\n\n3. Binning / Bucketizing\n\n3.1 Bucketizing using Pandas\n', '3.2 Bucketizing using Tensorflow\n\n3.3 Bucketizing using Scikit-learn\n\n4. Transformer\n\n4.1 Log-Transformer using Numpy\n\n4.2 Box-Cox Function using Scipy\n\n5. Normalize / Standardize\n\n5.1 Normalize and Standardize using Scikit-learn\n6. Feature Crossing\n\n6.1 Feature Crossing in Polynomial Regression\n6.2 Feature Crossing and the Kernel-Trick\n\n7. Principal Component Analysis (PCA)\n\n7.1 PCA using Scikit-learn\n\nSummary\n\nReferences\n\nIntroduction\n\nFeature engineering describes the process of formulating relevant features that describe the\nunderlying data science problem as accurately as possible and make it possible for\nalgorithms to understand and learn patterns. In other words:\n\nFeatures you provide serve as a way to communicate your own understanding\nand knowledge about the world to your model\n\nEach feature describes a kind of information “piece”. The sum of these pieces allows the\nalgorithm to draw conclusions about the target variables—at least if you have a data set that\nactually contains information about your target variable.\n\nAccording to the Forbes magazine, Data Scientists spend about 80% of their time collecting\nand preparing relevant data, with the data cleaning and data organizing alone taking up\nabout 60% of the time.\n\nBut this time is well spent.\n| believe that the quality of the data, as well as the proper preparation of the data set\n\nfeatures, have a greater impact on the success of a machine learning model than any other\npart of the ML pipeline:\n', '——— __ Data Retrieval\n\nMachine\nDatasets | Leaming\n\n(CU\n\nAlgorithm\n\nA Feature 7\nData Processing Feature Scaling Model\n= Extraction & < =, Deployment &\n& Wrangling Engineering & Selection —os Modeling — EvausioD é— Monitoring\nuning\nData Preparation\n\nA standard Machine Learning pipeline—Inspired by [Sarkar et al., 2018]\n\nWhat Forbes magazine considers as “cleaning and organizing” is usually broken down into\ntwo to three subcategories in the ML pipeline (I have highlighted them with a yellow\nbackground in the image above):\n\n(1) Data (Pre-)Processing: The initial preparation of the data—for example, smoothing a\nsignal, dealing with outliers, etc.\n\n(2) Feature engineering: Defining input features for our model—e.g., by converting an\n(acoustic) signal to the frequency domain using the fast Fourier transform (FFT) allows us to\nextract crucial information from the raw signal.\n\n(3) Feature Selection: Selection of features that have a significant impact on the target\nvariable. By selecting the important features and thus reducing the dimensionality, we can\nsignificantly reduce the modeling costs and increase the robustness and performance of the\nmodel.\n\nWhy do we need Feature Engineering?\n\nAndrew Ng frequently advocates a so-called data-centric approach, which emphasizes the\nimportance of selecting and curating data, rather than simply trying to collect more and more\ndata. The goal is to ensure that the data is of high quality and relevance to the problem\nbeing addressed and to continually improve the data set through data cleaning, feature\nengineering and data augmentation.\n\nWhy do we need feature engineering and a data-centric approach when we\nhave Deep Learning?\n\nThis approach is particularly useful for use cases where it is costly or otherwise difficult to\ncollect large amounts of data. [Brown, 2022] This might be the case when the data is difficult\nto access, or when there are strict regulations or other barriers to collecting and storing large\namounts of data, e.g.:\n\ne Inthe manufacturing sector, equipping production facilities with comprehensive\nsensor technology and connecting them to databases is expensive. As a result, many\nplants do not yet collect data at all. Even when machines are able to collect and store\ndata, they are rarely connected to a central data lake.\n', 'e Inthe supply chain context, every company has only a certain number of orders\nthat it processes every day. So if we want to predict the demand for a product that is\nin very irregular demand, we sometimes have only a few data points available.\n\nIn such areas, feature engineering probably has the greatest leverage to increase the\nperformance of the models. Here, the creativity of the engineers and data scientists is\nrequired to enhance the data set quality to a sufficient level. The process is rarely\nstraightforward, but rather experimental and iterative.\n\nWhen humans analyze data, they often use their past knowledge and experience to help\nthem understand patterns and make predictions. For example, if someone is trying to\nestimate the temperature in different countries, they might consider the location of the\ncountry relative to the equator, since they know that temperatures tend to be higher near the\nequator.\n\nHowever, a machine learning model does not have the same inherent understanding of\nconcepts and relationships as a human does. It can only learn from the data it is given.\nTherefore, any background information or context that a human would use to solve a\nproblem must be explicitly included in the data set in a numerical form.\n\nGB 25-28"\nBe 20-24°c\nBi 1s-19°¢\n(i 10-14\nBB ssc\nMe sarc\n\nAverage yearly temperature per country [Wikimedia]\nSo what data do we need to make the model smarter than a human?\n\nWe could use the Google Maps API to find the location coordinates (longitude and latitude)\nof each country. Additionally, we can gather information about the altitude of the region and\nthe distance from the nearest body of water for each country. By collecting this extra data,\nwe hope to identify and consider possible factors that could affect the temperature in each\ncountry.\n\nLet’s say we have collected some data that might have an impact on the\ntemperature, what next?\n', "Once we have enough data that describes the characteristics of the problem, we still have to\nmake sure that the computer can understand the data. Categorical data, dates, etc. must be\nconverted into numerical values.\n\nIn this article, | am describing a few commonly used techniques for preparing raw data.\nSome techniques are used to convert categorical data into numerical values that can be\nunderstood by the machine learning model, such as encoding and vectorizing. Other\ntechniques are used to address the distribution of the data, such as transformers and\nbinning, which can help to normalize or standardize the data in some way. Still, other\ntechniques are used to reduce the dimensionality of the dataset by generating new features,\nsuch as hashing and principal component analysis (PCA).\n\nTry it yourself...\n\nIf you want to follow the article and try the methods yourself, you can use the repo below,\nwhich contains the code snippets in a Jupyter Notebook and the data sets used:\n\nGitHub - polzerdo55862/7-feature-engineering-techniques\nYou can't perform that action at this time. You signed in with another tab or window. You\n\nSigned out in another tab or...github.com\n\n1. Encoding\n\nFeature encoding is a process used to transform categorical data into numerical values that\ncan be understood by ML algorithms. There are several types of encoding, including label\nencoding and one-hot encoding.\n\nsaw dateieet Label Encoding\nIndex Education\nBachelor 2 e @ °\n(1) (2] (3]\nMasters Bachelor Masters Doctorate\nDoctorate\nHot Encoding\nBachelor\n[0,1,0)\nDoctorate\n\n[1,0,0]\nMaster\n[1,0,0]\n\nLabel and Hot Encoding—Image by the author\n\nLabel encoding involves assigning a numeric value to each categorical value. This can be\neffective if there is an inherent order to the categorical values, such as grades from A to F,\nwhich can be encoded as numeric values from 1 to 5 (or 6). However, if there is no inherent\norder to the categorical values, label encoding may not be the best approach.\n", "Alternatively, you can use One-hot encoding to transform categorical values into numerical\nvalues. In one-hot encoding, the column of categorical values is split into several new\ncolumns, one for each unique categorical value.\n\nFor example, if the categorical values are grades from A to F:\n\ne we would have five new columns, one for each grade.\n\ne Each row in the dataset would have a value of 1 in the column corresponding to its\ngrade and 0 in all the other columns.\n\ne This results in a so-called sparse matrix, where most of the values are 0.\n\nThe disadvantage of one-hot encoding is that it can significantly increase the size of the\ndataset, which can be a problem if the column you want to encode contains hundreds or\nthousands of unique categorical values.\n\nIn the following | am using Pandas, Scikit-learn or Tensorflow to apply label and one-hot\nencoding to your data set. For the example below, we are using the Census Income data\nset:\n\nData set: Census Income [License: CC0: Public Domain\nhttps://archive.ics.uci.edu/ml/datasets/censustincome\nhttps://www.kaggle.com/datasets/uciml/adult-census-income\n\nThe Census Income Data set describes the income of individuals in the United\nStates. It includes their age, sex, marital status and other demographic\ninformation as well as their annual income, which is divided into two categories:\nover $50,000 or under $50,000.\n\nFor the labelling example, we are using the “education” column of the census data set, which\ndescribes the highest level of education achieved by individuals within the population. It\ncontains information such as whether an individual has completed high school, completed\ncollege, earned a graduate degree, or some other form of education.\n\nFirst, let’s load the data set:\nimport pandas as pd\n\n# load dataset - census income\ncensus_income = pd.read_csv(r'../input/income/train.csv')\n\n1.1 Label Encoding using Scikit-learn\n\nLabel encoding is the simplest way to convert categorical values into numerical values. It is a\nsimple process of assigning a numerical value to each category.\n", 'Doctorate 0\nBachelor 1\n12 2\nSome-college 3\nMasters 4\nHS-grad 5\n\nLabel Encoding— Image by the author\n\nYou can find suitable libraries in Pandas, Scikit-Learn and Tensorflow. | am using the\nScikit-Learns Label Encoder function. It is randomly assigning integers to the unique\ncategorical values, which is the simplest way of encoding:\n\nfrom sklearn import preprocessing\n\n# define and fit LabelEncoder\nle = preprocessing.LabelEncoder()\nle.fit(census_income["education"])\n\n# Use the trained LabelEncoder to label the education column\ncensus_income["education_labeled"] = le.transform(census_income["education"])\n\ndisplay(census_income[["education", "education_labeled"]])\n\neducation education labeled\nDoctorate 10\n12th 2\nBachelors 9\n7th-8th 5\n\nSome-college 15\n\nBachelors\n\nHS-grad\n\n43954 Some-college\n43955 Bachelors\n43956 HS-grad\n\n43957 rows x 2 columns\n\nThis way of encoding can cause problems for some algorithms because the assigned\nintegers do not necessarily reflect any inherent order or relationship between the categories.\nFor example, in the case described above, the algorithm may assume that the categories\n', 'Doctorate (10) and HS-grad (11) are more similar to each other than categories Doctorate\n(10) and Bachelor (9) and that HS-grad (11) is “higher” than Doctorate (10).\n\n[10]\nDoctorate\n0-0-0-0-@ 0-00-69 0-000\n[5] [9] {11]\n7Hh.Bth Bachelors HS-grad\n\nLabel Encoding result interpretation—Image by the author\n\nIf we have some knowledge about the specific domain or subject matter of a data set, we\ncan use it to ensure that the label encoding process reflects any inherent order. For our\nexample, we could try to label the education levels considering the order in which different\ndegrees are obtained, e.g.:\n\nDoctorate is a higher academic degree compared to a Master\'s and Bachelor\'s. The Master\'s\nis higher than the Bachelor\'s.\n\ne HS-grad — 1\ne Bachelors — 2\n\ne Masters — 3\n\ne Doctorate — 4\n\nTo apply this manual mapping to the data set, we can use the pandas.map function:\neducation_labels = {\'Doctorate\'’:5, \'Masters\':4, \'Bachelors\':3, \'HS-grad\':2, \'12th\':1, \'11th\':0}\n\ncensus_income[\'education_labeled_pandas\']=census_income[\'education\'].map(education_la\nbels)\n\ncensus_income|["education", "education_labeled_pandas"]]\n- education education_labeled_pandas\nDoctorate 5.0\n12th 1.0\nBachelors 3.0\n7th-8th\n\nSome-college\n\nBut how does this affect the model-building process?\n\nLet\'s build a simple linear regression model with the labeled encoded data:\n', 'For the figure below, the target variable is defined as the probability that an individual has\nan income of more than $50,000.\n\ne Inthe left figure, the categorical values (such as “Bachelor” and “Doctorate”) have\n\nbeen assigned randomly to numerical values.\ne Inthe right figure, the numerical values assigned to the categorical values reflect\n\nthe order in which the degrees are typically obtained, with higher education degrees\nbeing assigned higher numerical values.\n\n— The right figure shows a clear correlation between education level and income, which\ncould be represented by a simple linear model.\n\n— In contrast, the left figure shows a relationship between the education attribute and the\ntarget variable, which would require a more complex model to accurately represent. This\ncould affect the interpretability of the results, increase the risk of overfitting and increase the\ncomputational effort required to fit the model.\n\nLabel encoding: Random Order Label encoding: Order based on domain know-how\n\n07 ‘mm Linear Model 0.7. Sm Linear Model\n\n0.6\n2 g 06\nco} co\n£05 £05\n3 3S\n© 0.4 ® 0.4\n2 2\n3 0.3 503\ns g\n© 0.2 © 0.2\na a\n\n0.0 0.0\n\n2 3 1 2 3 4\nEducation Numeric Education Numeric\n\nLabel Encoding: Linear Regression Model trained on ordered and unordered “education”\n\nfeature—Image by the author\nWhat do we do when values have no inherent order or we don’t have enough\n\ninformation to map it?\n\nIf the categorical values do not have an inherent order at all, it may be better to use a\nmethod of encoding that converts the categories into a set of numeric variables without\nintroducing any bias. One-hot encoding is one suitable method.\n\n1.2 One-Hot Encoding using Scikit-learn, Pandas and Tensorflow\n\nOne-hot encoding is a technique for converting categorical data into numerical data. It does\nthis by creating a new binary column for each unique category in the data set and assigning\na value of 1 to rows that belong to that category and a value of 0 to rows that do not.\n\n— This process helps to avoid introducing bias into the data by not assuming any inherent\norder between the categories.\n', 'Raw data set\n\nEs hell!\n\n1 Bachelor\n2 Masters\n3 Doctorate ip\n\nDoctorate\n[1,0,0]\nMaster\n[1,0,0]\nBachelor Masters Doctorate\n1 1 0 0\n2 te) 1 0\n3 0 0 1\n\nOne-Hot Encoding—Image by the author\n\nThe process of One-Hot Encoding is pretty straightforward. We could simply implement it by\nourselves or use one of the existing functions. Scikit-learn has the\n.preprocessing.OneHotEncoder() function, Tensorflow the .one_hot() function, and\nPandas the .get_dummies() function.\n\ne Pandas.get_dummies()\nimport pandas as pd\n\neducation_one_hot_pandas = pd.get_dummies(census_income["education"],\nprefix=\'education’)\neducation_one_hot_pandas.head(2)\n\ne Sklearn.preprocessing.LabelBinarizer()\n\nfrom sklearn import preprocessing\n\nIb = preprocessing.LabelBinarizer()\nIb.fit(census_income["education"])\n\neducation_one_hot_sklearn_binar =\npd.DataFrame(Ib.transform(census_income["education"]), columns=lb.classes_)\neducation_one_hot_sklearn_binar.head(2)\n\ne Sklearn.preprocessing.OneHotEncoder()\n\nfrom sklearn.preprocessing import OneHotEncoder\n\n# define and fit the OneHotEncoder\nohe = OneHotEncoder()\nohe.fit(census_income[[\'education\']])\n', '# transform the data\neducation_one_hot_sklearn =\npd.DataFrame(ohe.transform(census_income[["education"]]).toarray(),\ncolumns=ohe.categories_[0])\neducation_one_hot_sklearn.head(3)\nThe problem with one-hot encoding is that it can lead to large and sparse\ndatasets with high dimensionality.\n\nUsing one-hot encoding to convert a categorical feature with 10,000 unique values into\nnumerical data would result in the creation of 10,000 new columns in the data set, each\nrepresenting a different category. This can be a problem when working with large data sets,\nas it can quickly consume a lot of memory and computational resources.\n\nIf memory and computer power are limited, it may be necessary to reduce the number of\nfeatures in the data set to avoid running into memory or performance issues.\n\nHow can we reduce dimensionality to save memory?\n\nWhen doing this, it is important to try to minimize the loss of information as much as\npossible. This can be achieved by carefully selecting which features to retain or remove, by\nusing techniques such as feature selection or dimensionality reduction to identify and\nremove redundant or irrelevant features. [Sklearn.org][Wikipedia, 2022]\n\nIn this article | am describing two possible ways how to reduce the dimensionality of your\ndata set:\n\n1. Feature Hashing—see section 2. Feature Hashing\n2. Principal Component Analysis (PCA)—see section 7. PCA\n\nLoss of information vs. speed vs. memory\n\nThere is probably not one “perfect” solution for reducing the number of dimensions in your\ndata set. One method may be faster but may result in the loss of a lot of information, while\nthe other method preserves more information but requires a lot of computing resources\n(which may also lead to memory issues).\n\n2. Feature Hashing\n\nFeature hashing is primarily a dimensionality reduction technique and is often used in\nNatural Language Processing. However, hashing can also be useful when we want to\nvectorize categorical features with several hundred and thousand unique categories.\nWith hashing, we can limit the increase of dimensionality by assigning several unique values\nto the same hash value.\n\n— Hashing is thus a low-memory alternative to OneHotEncoding and other feature\nvectorizing methods.\n', 'Hashing works by applying a hash function to the features and using the hash values directly\nas indices, rather than building a hash table and looking up indices in it individually. The\nimplementation in Sklearn is based on Weinberger [Weinberger et al., 2009].\n\nWe can break it down into 2 steps:\n\ne Step 1: the categorical values are first converted to a hash value using a hash\nfunction. The implementation in Scikit-learn uses the 32-bit variant of MurmurHash3\nfor this.\n\nHash Function\n\n1 Bachelor 1 -1182795914\nSeanad Se een\n\n2 Masters 2 387459256\n\n3 Doctorate 3 325975461\n\n4 4\n\ne.g. MurmurHash3\n\nHashing Trick—Image by the author\n\nimport sklearn\nimport pandas as pd\n\n# Load data set\n\ncensus_income = pd.read_csv(r\'../input/income/train.csv\')\neducation_feature =\ncensus_income.groupby(by=["education"]).count().reset_index()["education\n"].to_frame()\n\nTARTRATE EAE AE TET ETE TEE EEE TEE TTT EAT TET EEE TE TET TEE EE\n\n# Apply the hash function, here MurmurHash3\n\nTARTRATE EAE AE TET ETE TEE EEE TEE TTT EAT TET EEE TE TET TEE EE\n\ndef hash_function(row):\nreturn(sklearn.utils.murmurhash3_32(row.education) )\n\neducation_feature["education_hash"] =\neducation_feature.apply(hash_function, axis=1)\neducation_feature\n\n', 'education education_hash\n10th 611946777\n\n11th 

Newer OCR engines (EasyOCR, PaddleOCR)\
Improved accuracy on handwriting and complex layouts while maintaining local
deployment benefits

### 1.7 Extracting Text from Images using Multimodal Models

In [32]:
import base64
from openai import OpenAI

png_file_path = "../../datasets/images/example_finance_reporting_slide.png"

# initialize the OpenAI client
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

with open(png_file_path, "rb") as image_file:
    base64_image = base64.b64encode(image_file.read()).decode("utf-8")

    prompt = (
        "Extract the text from the image attached. Make sure to only "
        "extract only the text. If there is no text in the image, "
        "please return with the sentence 'No text found in the image."
    )

    response = client.chat.completions.create(
        model="gpt-4o-mini",  # define the model to use
        messages=[
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": prompt},
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": (
                                f"data:image/jpeg;base64,"
                                f"{base64_image}"
                            ),
                        },
                    },
                ],
            }
        ],
        max_completion_tokens=500,
    )

    content = response.choices[0].message.content
    print(content)

Sales volume growth driven by EMEA 18/19

Business Development

• Sales volume growth driven by EMEA with sales activity up to 2.3x YoY

• Sales activity in 20 countries during Q2 19
  • US (28%), Spain (20%), India (15%) and Norway (11%) are the main contributors to the Q2 19 sales volume

### 1.8 Generating Text Summaries for Images Using Multimodal Models

In [33]:
import base64
from openai import OpenAI

image_path = "../../datasets/images/vietnam.png"

# initialize the OpenAI client
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

with open(image_path, "rb") as image_file:
    base64_image = base64.b64encode(image_file.read()).decode("utf-8")

    prompt = (
        "You are an assistant for visually impaired users. "
        "Describe the image in detail."
    )

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": prompt},
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": (
                                f"data:image/jpeg;base64,"
                                f"{base64_image}"
                            ),
                        },
                    },
                ],
            }
        ],
        max_completion_tokens=150,
    )

    content = response.choices[0].message.content
    print(content)

The image depicts a vibrant city skyline at dusk, showcasing a mix of modern architecture and beautiful waterfront views.

On the left side, there is a uniquely shaped skyscraper with a pointed top, which stands out prominently among the other buildings. Next to it, multiple glass high-rises with a variety of designs gleam with lights as night begins to fall. The buildings display a range of colors, reflecting the city’s dynamic energy.

The waterfront is calm and features a gentle ripple effect where the water reflects the colors of the sky and the illuminated structures. In the foreground, there appears to be a dock or pier with a boat, adding a sense of movement to the scene.

The sky showcases a gradient effect, transitioning from soft blues to pur

### 1.9 Generating Text Summaries for Embedded Tables Using Multimodal Models

In [ ]:
from unstructured.partition.pdf import partition_pdf

pdf_file_path = "../../datasets/pdf_files/adult_data_article.pdf"

tables = []
texts = []

# partition the PDF file into its elements
raw_pdf_elements = partition_pdf(
    filename=pdf_file_path,
    strategy="hi_res",
)

for element in raw_pdf_elements:
    if "unstructured.documents.elements.Table" in str(type(element)):
        tables.append(str(element))

In [ ]:
from openai import OpenAI
import pandas as pd

def summarize_tables(row):
    summary_prompt = (
        f"You are an assistant tasked with summarizing tables. "
        f"Give a concise summary of the table. "
        f"Table chunk: {row.table}"
    )

    # Initialize the OpenAI API client and generate table summary
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
    response = client.chat.completions.create(
        model="gpt-5-nano",
        messages=[{"role": "user", "content": summary_prompt}],
        temperature=0.7,
        max_tokens=150,
    )

    row["table_summary"] = response.choices[0].message.content

    return row


# create a pandas dataframe from the tables
tables_df = pd.DataFrame(tables, columns=["table"])

# add a column to the dataframe to store the summaries
tables_df = tables_df.apply(summarize_tables, axis=1)

In [ ]:
# define a random question to the embedded table
user_question = "What are the education levels of the people working in Sales?"


def build_prompt_and_generate_answer(user_question, found_table):
    """
    This function builds a prompt using the user's question and the context of the table
    and generates an answer using the OpenAI API

    Parameters:
        user_question: the question asked by the user
        found_table: the table context to generate the answer from

    Returns:
        answered_question: the answer to the user's question
    """

    question_prompt = f"""You are an assistant using the content from PDFs \
                        to answer questions. Below you can find the \
                        user's question and relevant context. Please use the \
                        context to generate an answer to the user's question.

                        # User question: {user_question}

                        # Context:

                        ## Table summary:
                        {found_table.table_summary}

                        ## Table content:
                        {found_table.table}""".strip()

    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

    answered_question = (
        client.chat.completions.create(
            model="gpt-4o",
            messages=[{"role": "user", "content": question_prompt}],
            temperature=0.7,
            max_tokens=150,
        )
        .choices[0]
        .message.content
    )

    return answered_question


# generate the answer to the user's question
# as context we using the first entry in the tables_df
answered_question = build_prompt_and_generate_answer(
    user_question=user_question, found_table=tables_df.iloc[0]
)

print(answered_question)

The individuals working in Sales have the following education levels:

1. Some-college
2. HS-grad (High School Graduate)
3. Some-college
4. Bachelors

### 1.10 Parsing PDFs with Multiple Media Content Using Unstructured and Multimodal Models

In [ ]:
from unstructured.partition.pdf import partition_pdf
import os

# set the OCR agent to tesseract
os.environ["OCR_AGENT"] = "tesseract"

pdf_file_path = "../../datasets/pdf_files/adult_data_article.pdf"
image_output_dir = "../../datasets/extracted_content_from_pdfs/images"

# create output directory if it doesn't exist
os.makedirs(image_output_dir, exist_ok=True)

# get elements using the function extract_pdf_elements
raw_pdf_elements = partition_pdf(
    filename=pdf_file_path,
    extract_images_in_pdf=True,
    extract_image_block_types=["Image", "Table"],
    extract_image_block_to_payload=False,
    extract_image_block_output_dir=image_output_dir,
)

# categorize elements by type
tables = []
texts = []
titles = []

# fill the just created lists with the elements
for element in raw_pdf_elements:
    element_type = str(type(element))
    if "unstructured.documents.elements.Table" in element_type:
        tables.append(str(element))
    elif "unstructured.documents.elements.NarrativeText" in element_type:
        texts.append(str(element))
    elif "unstructured.documents.elements.Title" in element_type:
        titles.append(str(element))

### 1.11 Loading Videos Using Speech-to-Text and Multimodal Models

In [ ]:
import os
import pandas as pd

from moviepy import VideoFileClip, TextClip, CompositeVideoClip

video_file_path = "../datasets/videos/learn-data-science-tutorial.mp4"
image_output_folder = "../datasets/videos/video_extracted_images"

# create output folder if it doesn't exist
os.makedirs(image_output_folder, exist_ok=True)

# Check if the video file exists
if os.path.exists(video_file_path):
    clip = VideoFileClip(video_file_path)

    # create a list of timestamps from which to extract a frame
    time_step = 10  # time in seconds
    timestamps = list(range(0, int(clip.duration) - time_step, time_step))

    # for each timestamp extract a frame
    for timestamp in timestamps:
        frame_image_path = os.path.join(
            image_output_folder, f"frame_{timestamp}.png"
        )
        clip.save_frame(frame_image_path, t=timestamp)
else:
    print(f"Video file not found: {video_file_path}. Skipping video processing.")
    timestamps = [] # Ensure timestamps is defined even if file not found

In [ ]:
# for each timestamp extract the audio sequence and save it to a .mp3 file
audio_output_folder = "../datasets/videos/video_extracted_audio"

# create output folder if it doesn't exist
os.makedirs(audio_output_folder, exist_ok=True)

for timestamp in timestamps:
    audio_clip = clip.subclip(timestamp, timestamp + time_step).audio
    output_audio_path = os.path.join(
        audio_output_folder, f"audio_{timestamp}.mp3"
    )
    audio_clip.write_audiofile(output_audio_path)

In [ ]:
import os
from openai import OpenAI


def audio_to_text(audio_path):
    """
    Convert audio to text using OpenAI's Whisper model.
    """

    if not os.path.exists(audio_path):
        print(f"[ERROR] File does not exist: {audio_path}")
        return None

    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

    try:
        with open(audio_path, "rb") as audio_file:
            transcription = client.audio.transcriptions.create(
                model="whisper-1",
                file=audio_file
            )

        text_file_path = os.path.splitext(audio_path)[0] + ".txt"

        with open(text_file_path, "w", encoding="utf-8") as text_file:
            text_file.write(transcription.text)

        return transcription.text

    except FileNotFoundError:
        print(f"[ERROR] File not found during processing: {audio_path}")
    except PermissionError:
        print(f"[ERROR] Permission denied: {audio_path}")
    except Exception as e:
        print(f"[ERROR] Failed to process {audio_path}: {e}")

    return None


# Process folder
audio_files = os.listdir(audio_output_folder)

for audio_file in audio_files:
    absolute_path_audio_file = os.path.join(audio_output_folder, audio_file)

    # No need to check exists here anymore, function handles it
    result = audio_to_text(audio_path=absolute_path_audio_file)

    if result is None:
        print(f"Skipping file: {absolute_path_audio_file}")